# Generated by Django 5.2.6 on 2026-08-08 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_add_deadline_escalation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='If set, only these users can see and submit this form.', related_name='assigned_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
