# Generated by Django 5.2.6 on 2026-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_magic_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclinktoken',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='magiclinktoken',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
